language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "jinfei21" 
  - git config user.email "63581560@qq.com" 
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`" 
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

  
branches:
  only:
    - code
env:
 global:
   - GH_REF: github.com/jinfei21/jinfei21.github.io.git
   
notifications:
  email:
    - 63581560@qq.com
  on_success: change
  on_failure: always